### ISSUE TITLE
粵拼方案容錯/教院式兼容無效

### ISSUE THREAD

**Issue by konzertnr9** [osfans/PRIME#10]
jyutping_schema.yaml裡面有一串容錯/教院式兼容設定：
  algebra:
    - derive/^jy?([aeiou])/y$1/  # 容錯 je -> ye, jyu -> yu
    - derive/^jyu/ju/            # 容錯 jyu -> ju
    - derive/yu/y/               # 教院式 jyu -> jy
    - derive/eoi$/oey/           # 教院式
    - derive/eoi$/eoy/           # 容錯
    - derive/eo/oe/              # 教院式
    - derive/oe(ng|k)$/eo$1/     # 容錯
    - derive/aa$/a/              # 容錯
    - abbrev/^([a-z]).+$/$1/     # 首字母簡拼
    - derive/^z/dz/              # 教院式
    - derive/^c/ts/              # 教院式
    - abbrev/^(ng).+$/$1/        # 聲母簡拼
    - abbrev/^([gk]w).+$/$1/     # 聲母簡拼
    - abbrev/^(dz).+$/$1/        # 聲母簡拼
    - abbrev/^(ts).+$/$1/        # 聲母簡拼
當使用粵拼方案輸入時卻未能發揮作用。

**Comment by konzertnr9** [comment]
上述現象發生於Windows 10 Creators Update上，在Windows 7並沒有出現。

**Comment by osfans** [comment]
這個可能要註銷一下，在重新進系統。

**Comment by konzertnr9** [comment]
重新登入沒有解決問題，之後把用戶資料夾裡的jyutping*.*除了shema.yaml刪掉後重新部署就解決了。
謝謝！
