### ISSUE TITLE
如何设置竖排？

### ISSUE THREAD

**Issue by ipcjs** [osfans/PRIME#14]
我记得以前，default.yaml里的"menu/page_size"控制候选词总个数，PIME.yaml里的"style/candidate_per_row"控制每行候选词的个数，两个数字设成一样，就是横排了。
但今天在对应的*.custom.yaml文件中，把这两行注释掉之后，并没有变回竖排。。。是BUG吗？

环境：
Win10 + Prime 0.16.1

**Comment by ipcjs** [comment]
好奇怪，又正常了。。。

**Comment by osfans** [comment]
可能要註銷才能正常。
