### ISSUE TITLE
Windows 10 User 目錄下未生成 PIME 文件夾

### ISSUE THREAD

**Issue by hanabinoir** [osfans/PRIME#15]
下載並安裝了 PRIME 的 0.16.1 版本，想修改配置文件，但是並未在 c:\users\[user] 中找到 PIME 文件夾，不知是何原因。

**Comment by InSb** [comment]
應是`C:\Users\[使用者名]\AppData\Roaming\PIME`。`AppData`是隱藏文件夾。
或者直接在語言欄的「中」圖標上右擊->打開文件夾->用戶文件夾，等。
