### ISSUE TITLE
數字鍵盤區的回車鍵有問題

### ISSUE THREAD

**Issue by KiritoStudio** [osfans/PRIME#7]
打字的時候發現回車鍵跟數字鍵盤區的回車鍵在輸入的時候好像功能不一致，拼音選字的時候按回車鍵是會直接打英文的，但是數字鍵盤區的回車鍵卻沒反映，看上去應該是個bug？

**Comment by osfans** [comment]
跟主鍵盤不同，是KP_Enter

**Comment by KiritoStudio** [comment]
是需要什麼設定嗎？

**Comment by osfans** [comment]
https://github.com/rime/rime-prelude/blob/master/default.yaml#L106

具體參考這個。可以將KP_Enter轉發爲Return

**Comment by KiritoStudio** [comment]
Nice，加入
- { when: composing, accept: KP_Enter, send: Return }
後，重新部署一下就可以了
